using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CamerMotor : MonoBehaviour
{
    //Declare Variables
    private Transform lookAt;
    public float boundX = 0.15f;
    public float boundY = 0.05f;

    private void Start()
    {
        lookAt = GameObject.Find("Player").transform;
    }

    private void LateUpdate()
    {
        //Reset the camera position
        Vector3 delta = Vector3.zero;

        //Determine the positions and move them
        //Horizontal
        float deltaX = lookAt.position.x - transform.position.x;
        if (deltaX > boundX || deltaX < -boundX)
        {
            if (transform.position.x < lookAt.position.x)
            {
                delta.x = deltaX - boundX;
            }
            else
            {
                delta.x = deltaX + boundX;
            }
        }
        //Vertical
        float deltaY = lookAt.position.y - transform.position.y;
        if (deltaY > boundY || deltaY < -boundY)
        {
            if (transform.position.y < lookAt.position.y)
            {
                delta.y = deltaY - boundY;
            }
            else
            {
                delta.y = deltaY + boundY;
            }
        }
        //Move the camera
        transform.position += new Vector3(delta.x, delta.y, 0);
    }
}
